### ISSUE TITLE
Error occurs when the default difficulty is used

### ISSUE THREAD

**Issue by srz2** [srz2/BeginnerProjectBot#9]
Exception in thread Comment Stream Checker:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "/Users/stevenzilberberg/Desktop/BeginnerProjectBot/src/bot.py", line 78, in run
    stream_subreddits_comments(self.reddit)
  File "/Users/stevenzilberberg/Desktop/BeginnerProjectBot/src/bot.py", line 536, in stream_subreddits_comments
    get_idea_and_respond_comment(comment, difficulty)
  File "/Users/stevenzilberberg/Desktop/BeginnerProjectBot/src/bot.py", line 478, in get_idea_and_respond_comment
    idea = get_random(ideas, difficulty)
  File "/Users/stevenzilberberg/Desktop/BeginnerProjectBot/src/bot.py", line 366, in get_random
    tmp_ideas = ideas[desired_difficulty]
KeyError: 'none'

**Comment by srz2** [comment]
This seems to be because when the bot try to use the default difficulty of 'none', it doesn't exist in the dictionary of ideas

Therefore the keyword should change to 'all'
